Hwc wasa changes
PSMRI/HWC-UI pull request #73
Opened 2024-11-29 15:04 UTC by NKOKKILIGADDA87

## 📋 Description

JIRA ID: 

Please provide a summary of the change and the motivation behind it. Include relevant context and details.

---

## ✅ Type of Change

- [ ] 🐞 **Bug fix** (non-breaking change which resolves an issue)
- [ ] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🔥 **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🛠 **Refactor** (change that is neither a fix nor a new feature)
- [ ] ⚙️ **Config change** (configuration file or build script updates)
- [ ] 📚 **Documentation** (updates to docs or readme)
- [ ] 🧪 **Tests** (adding new or updating existing tests)
- [ ] 🎨 **UI/UX** (changes that affect the user interface)
- [ ] 🚀 **Performance** (improves performance)
- [ ] 🧹 **Chore** (miscellaneous changes that don't modify src or test files)

---

## ℹ️ Additional Information

Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

2024-11-29 15:40 UTC, sandipkarmakar3 commented
@coderabbitai review

2024-11-29 15:43 UTC, sandipkarmakar3 commented
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-23 08:47 UTC, sandipkarmakar3 reviewed
All changes I have reviewed.
Everything is as per the requirement.
We used sessionstorage.service to store the data to session storage.
We removed all localstorage code and used session storage.
We used jwt token for validate user's session.

2025-01-28 10:34 UTC, devikasuresh20 requested changes

2025-01-28 10:34 UTC, devikasuresh20 commented on src/app/app-modules/core/components/app-header/app-header.component.ts
> +    readonly sessionstorage: SessionStorageService,
consider using camelCase for variable names as per typescript naming convention

2025-01-28 10:34 UTC, devikasuresh20 commented on WEB-INF/jboss-web.xml
> +  <context-root>/hwc-wasa</context-root>
Please keep "/hwc" as context-root

2025-01-28 10:34 UTC, devikasuresh20 commented on src/environments/environment.development.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
@sandipkarmakar3 The current war for hwc-facility-service doesn't have a version. Please remove "-v1.0" from URL.

2025-01-28 10:34 UTC, devikasuresh20 commented on src/environments/environment.development.ts
> +  INVENTORY_URL: `${inventoryUI_IP}/hwc-inventory-wasa/#/redirin?`,
@sandipkarmakar3 Remove "-wasa" from inventory URL

2025-01-28 10:34 UTC, devikasuresh20 commented on src/environments/environment.development.ts
> +  TELEMEDICINE_URL: `${schedulerUI_IP}/hwc-scheduler-wasa/#/?`,
@sandipkarmakar3 Remove "-wasa" from scheduler URL

2025-01-28 10:42 UTC, devikasuresh20 requested changes

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.prod.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
@sandipkarmakar3 The current war for hwc-facility-service doesn't have a version. Please remove "-v1.0" from URL

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.prod.ts
> +  INVENTORY_URL: `${inventoryUI_IP}/hwc-inventory-wasa/#/redirin?`,
@sandipkarmakar3  Remove "-wasa" from inventory URL

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.prod.ts
> +  TELEMEDICINE_URL: `${schedulerUI_IP}/hwc-scheduler-wasa/#/?`,
@sandipkarmakar3  Remove "-wasa" from scheduler URL

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.test.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
@sandipkarmakar3 The current war for hwc-facility-service doesn't have a version. Please remove "-v1.0" from URL

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.test.ts
> +  INVENTORY_URL: `${inventoryUI_IP}/hwc-inventory-wasa/#/redirin?`,
@sandipkarmakar3  Remove "-wasa" from Inventory URL

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.test.ts
> +  TELEMEDICINE_URL: `${schedulerUI_IP}/hwc-scheduler-wasa/#/?`,
@sandipkarmakar3 Remove "-wasa" from scheduler URL

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.ts
> +const TM_API = `${tmIP}/hwc-facility-service-v1.0/`;
@sandipkarmakar3 The current war for hwc-facility-service doesn't have a version. Please remove "-v1.0" from URL

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.ts
> +  INVENTORY_URL: inventoryUI_IP + '/hwc-inventory-wasa/#/redirin?',
@sandipkarmakar3 Remove "-wasa" from inventory URL

2025-01-28 10:42 UTC, devikasuresh20 commented on src/environments/environment.ts
> +  TELEMEDICINE_URL: schedulerIP + '/hwc-scheduler-wasa/#/?',
@sandipkarmakar3  Remove "-wasa" from Scheduler URL

2025-01-28 12:19 UTC, sandipkarmakar3 commented on src/environments/environment.ts
> +  TELEMEDICINE_URL: schedulerIP + '/hwc-scheduler-wasa/#/?',
done

2025-01-28 12:19 UTC, sandipkarmakar3 commented on src/environments/environment.ts
> +  INVENTORY_URL: inventoryUI_IP + '/hwc-inventory-wasa/#/redirin?',
done

2025-01-28 12:19 UTC, sandipkarmakar3 commented on src/environments/environment.ts
> +const TM_API = `${tmIP}/hwc-facility-service-v1.0/`;
done

2025-01-28 12:19 UTC, sandipkarmakar3 commented on src/environments/environment.test.ts
> +  TELEMEDICINE_URL: `${schedulerUI_IP}/hwc-scheduler-wasa/#/?`,
done

2025-01-28 12:19 UTC, sandipkarmakar3 commented on src/environments/environment.test.ts
> +  INVENTORY_URL: `${inventoryUI_IP}/hwc-inventory-wasa/#/redirin?`,
done

2025-01-28 12:19 UTC, sandipkarmakar3 commented on src/environments/environment.test.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
done

2025-01-28 12:19 UTC, sandipkarmakar3 commented on src/environments/environment.prod.ts
> +  TELEMEDICINE_URL: `${schedulerUI_IP}/hwc-scheduler-wasa/#/?`,
done

2025-01-28 12:20 UTC, sandipkarmakar3 commented on src/environments/environment.prod.ts
> +  INVENTORY_URL: `${inventoryUI_IP}/hwc-inventory-wasa/#/redirin?`,
done

2025-01-28 12:20 UTC, sandipkarmakar3 commented on src/environments/environment.prod.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
done

2025-01-28 12:20 UTC, sandipkarmakar3 commented on src/environments/environment.development.ts
> +  TELEMEDICINE_URL: `${schedulerUI_IP}/hwc-scheduler-wasa/#/?`,
done

2025-01-28 12:20 UTC, sandipkarmakar3 commented on src/environments/environment.development.ts
> +  INVENTORY_URL: `${inventoryUI_IP}/hwc-inventory-wasa/#/redirin?`,
done

2025-01-28 12:20 UTC, sandipkarmakar3 commented on src/environments/environment.development.ts
> +const TM_API = `${tmIP}hwc-facility-service-v1.0/`;
done

2025-01-28 12:20 UTC, sandipkarmakar3 commented on WEB-INF/jboss-web.xml
> +  <context-root>/hwc-wasa</context-root>
done

2025-01-28 12:21 UTC, sandipkarmakar3 commented on src/app/app-modules/core/components/app-header/app-header.component.ts
> +    readonly sessionstorage: SessionStorageService,
sesstionstorage we can't make it "sessionStorage" as its a default keyword in JS.

2025-01-29 05:16 UTC, merged